### PR TITLE
Updated content for OSS registrations confirmation email VEOSS-228

### PR DESCRIPTION
**Pull request by susan-badel**

### CODE REVIEW

**Review by valydia — APPROVED** [review]

**Review by valydia — CHANGES_REQUESTED** [review]
There's seem to be an issue with formatting https://build.tax.service.gov.uk/job/DC/job/hmrc-email-renderer-pr-builder/897/console:
```
com.lucidchart.sbt.scalafmt.ScalafmtCheckFailure: 1 Scala source not formatted in hmrc-email-renderer:compile
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$23$$anonfun$apply$21.apply(ScalafmtCorePlugin.scala:195)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$23$$anonfun$apply$21.apply(ScalafmtCorePlugin.scala:193)
	at scala.Option.foreach(Option.scala:236)
	at com.lucidchar
```
Any chance you could run `scalafmt` please?

**Review by valydia — CHANGES_REQUESTED** [review]
Looks like there is more formatting to do https://build.tax.service.gov.uk/job/DC/job/hmrc-email-renderer-pr-builder/898/console:
```
/home/jenkins/workspace/DC/hmrc-email-renderer-pr-builder/test/uk/gov/hmrc/hmrcemailrenderer/templates/oss/OSSRegistrationConfirmationSpec.scala has changes after scalafmt
com.lucidchart.sbt.scalafmt.ScalafmtCheckFailure: 1 Scala source not formatted in hmrc-email-renderer:test
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$23$$anonfun$apply$21.apply(ScalafmtCorePlugin.scala:195)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$23$$anonfun$apply$21.apply(ScalafmtCorePlugin.scala:193)
	at scala.Option.foreach(Option.scala:236)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$23.apply(ScalafmtCorePlugin.scala:193)
```
Could you please run `test:scalafmt`?

**Review by valydia — CHANGES_REQUESTED** [review]
Thank you for the formatting, the build is now failing (unit test) with the following https://build.tax.service.gov.uk/job/DC/job/hmrc-email-renderer-pr-builder/899/console:
```
PreviewSpec:

- should be able to render oss_registration_confirmation *** FAILED ***
[info]   Left(TemplateRenderFailure(key not found: lastDayOfCalendarQuarter)) matched the given pattern (PreviewSpec.scala:60)
```
Could you fix it please?

**Comment by susan-badel** [comment]
Sorry about that. Should be sorted now :)

**Review by masahmad — APPROVED** [review]

**Comment by valydia** [comment]
No worries - thank you for your swift updates

**Review by valydia — APPROVED** [review]

**Pull request merged**
