### PR TITLE
SCRS-3621 added register your company welcome email

### PR DESCRIPTION
**Pull request by Daveo-G**

### CODE REVIEW

**Comment by bejulshah** [comment]
- The new template is missing a h1 title, this has been standardised with all our email templates. Your service already has an existing template that was approved and it contains the h1 header title. 
See https://www-qa.tax.service.gov.uk/hmrc-email-renderer/test-only/preview/html/register_your_company_verification_email?verificationLink=http:%2F%2Fhost:8080%2Fyour%2Flink%2Faab2913c-2b50-412e-b96d-e9e394ffa199
- also on the existing template the sign off is different to this new template. Please use one sign off to keep the emails standardised. The existing template uses "A joint service from HMRC and Companies House".
- There is a link on the new template, has this been signed off with the content designers and/or with Digital Contact's DSM Trilly Chatterjee?
- If the link is allowed, it looks a bit wrong. It appears as registeryourcompany.gov.uk and when I click it on local machine preview mode, it takes me to hmrc-email-renderer service. This link looks like it will not work in production.

**Comment by bejulshah** [comment]
- This pull request causes unit test to fail. On your local machine run sbt clean test. you will see that uk.gov.hmrc.hmrcemailrenderer.templates.TemplateLocatorSpec test fails (reason could be the new template was not added to this test)

**Comment by Daveo-G** [comment]
Hi @bejulshah.  I've done some fixing!!
I have added in an h1 title onto the company welcome email (both html and txt versions).  
After speaking with our design team they decided that the common signoff for both templates should be "HMRC and Companies House"  I have therefore updated the existing template "register_your_company_verification_email" with this signoff and left the new one as is.
Regarding the link in the email I have spoken with the SCRS Product manager Daniel Swales and he is now in conversation with Trilly.  I have also demoed both templates to him this morning and he is happy with them.  
The value of the link hasn't been decided yet but the SCRS application will pass this through as a parameter when it is known.
I have also fixed the unit tests (really sorry about that one!!)

I guess you'll need the final go-ahead from Trilly but hopefully everything else is Ok.

**Comment by bejulshah** [comment]
Thanks.

I have had a look. 
One small change. With the sign-off, please include the word "From" to be consistent with all email templates. 
So it should be "From HMRC and Companies House"

**Comment by Daveo-G** [comment]
I've added the word 'From' to all the 'register your company' templates.
Many thanks

**Pull request merged**
